import { Lato } from "next/font/google";
import Nav from "./components/molecules/Nav/Nav.jsx";
import "./globals.css";
import Footer from "./components/molecules/Footer/Footer";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "900", "300", "100", "700"],
  display: "swap",
});
export const metadata = {
  title: "Booky",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Nav />
      <body className={lato.className}>{children}</body>
      <Footer />
    </html>
  );
}
